name: Elixir CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MIX_ENV: test

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu20

    strategy:
      matrix:
        elixir: [1.12.3, 1.13.4, 1.14.5, 1.15.4]
        erlang: [22.3, 23.3, 24.3, 25.3, 26.0]
        exclude:
          - elixir: 1.12.3
            erlang: 25.3
          - elixir: 1.12.3
            erlang: 26.0
          - elixir: 1.13.5
            erlang: 26.0
          - elixir: 1.14.5
            erlang: 22.3
          - elixir: 1.15.0
            erlang: 22.3
          - elixir: 1.15.0
            erlang: 23.3

    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.erlang }}
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.erlang }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.erlang }}-${{ matrix.elixir }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
